### ISSUE TITLE
View resources linked to particular resource

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#18]
I think it might be useful for a user to view resources linked resources (resources which point to it). This would make use of FHIR search API's chained resource queries. 

What do you think? 

For example clicking on the blue link button below:
![image](https://user-images.githubusercontent.com/10283712/74755807-aef70e80-5241-11ea-99dc-3be1c6c6b36f.png)

Would allow the user to see a table like this:

| Base Type | Profile | Count | 
----------- | ------- | ------ | 
Observation | PhenotypicFeature | 204
Specimen | None | 2
Condition | Diagnosis | 1

Clicking one of the rows above ^ would then result in a resource list view, similar to what we already display when a user clicks on a card from the home page.

**Comment by znatty22** [comment]
When this feature is implemented it will really help us test our use of references. For example, right now there's a question of what goes in the reference: 

https://github.com/kids-first/kf-model-fhir/pull/78#discussion_r382604225

**Comment by abgeorge7** [comment]
@znatty22 In the table above, does "count" refer to the **total** number of resources of that type or the number of resources of that type that reference the ID?

**Comment by znatty22** [comment]
@abgeorge7 the latter - total num of resources of that type that reference the given ID
