### ISSUE TITLE
All list views should support highlight row on hover

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#29]
Sorry should have been more clear about this! Right now I only see the highlight on hover for the home page list view and in the table of references list view. 

Can you add this feature to every list view we have so we have consistent behavior across the UI?

**Comment by abgeorge7** [comment]
I removed it from the details table because the rows now have two icons that can be clicked to display two different views - the highlighted row on hover looked like the row was clickable but its not, the icons are so I thought it was confusing behavior. what do you think?

**Comment by znatty22** [comment]
Ohhh hmm yea i see what you mean...Ok let's leave it the details table the way it is

**Comment by abgeorge7** [comment]
Okay! so this issue is good to close?
