### ISSUE TITLE
Charts show 0 valued items 

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#39]
Not sure if this is a bug or the data. Wondering why the charts are showing enumerated items with 0 value? Are there actually resources that have this value populated but the value is showing as 0?

![image](https://user-images.githubusercontent.com/10283712/76762830-68c19c00-6768-11ea-9735-034bca86e827.png)

**Comment by abgeorge7** [comment]
No, not a bug. The bar chart is showing all attribute values including the ones with 0 as the value. When I filtered them out the chart couldn't calculate its height and width correctly so I just kept them in. Can revisit if it's confusing

**Comment by znatty22** [comment]
So the bar chart is displaying all of the possible codes from the CodeSystem and any terms with 0 value means that no resources have that term. I think I understand now. Correct me if I'm wrong tho.

I still think it might be better to only show the set of terms which have non zero values. That way you don't have to scroll through a long list to find the ones that are represented in the data for the resource type.

**Comment by abgeorge7** [comment]
Okay - I can look into it. It was having some weird rendering problems before but I agree scrolling through hundreds of empty attributes isn't great
