### ISSUE TITLE
Replace hardcoded URLs with a variable for a default URL

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#51]
![image](https://user-images.githubusercontent.com/10283712/77366161-d0aa5080-6d2d-11ea-83dd-9dbae996c8be.png)

I think the default IP address should be hardcoded once in a config file (e.g. `DEFAULT_SERVER_URL=10.10.1.191:8000`) and then all other parts of the code that need to reference that url, should use the variable.

**Comment by abgeorge7** [comment]
It is in a config file - the 10.10.1.191 "next" links return with "localhost" in the url so there is some code to replace "localhost" with '10.10.1.191" if the returned url has that.

But I can make those use the variable too
