### ISSUE TITLE
Assume basic auth for our dev FHIR servers

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#52]
I think this would be temporary until we figure out something for #24 , but could we make it so that the dashboard app uses basic auth (via user login) for server IPs that are in our dev IP range? Could even make it easier and just check if `REACT_APP_FHIR_API` IP starts with `10.10.1`.

I'm deploying another FHIR server with our KF model and I'd like to be able to switch between the Phenopackets server and the KF FHIR server easily.

**Comment by abgeorge7** [comment]
Do you want to close this in favor of #24  ?
