### ISSUE TITLE
Add dev FHIR servers to default list

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#56]
Once the KF server has been deployed it would be really nice if we could switch between KF and Phenopackets. Could we seed the server IP drop down with:

- HAPI
- Phenopackets (will point to 10.10.1.191:8000)
- Kids First (will point to TBD)

If someone sets the `REACT_APP_FHIR_API` env var to something that is not in that list (like 127.0.0.1) then that IP should be added to the list so that a user may always switch back to the server they launched the app for initially.

**Comment by abgeorge7** [comment]
I can add this when we have the url for the Kids First server 👍
