### ISSUE TITLE
Enable switch server drop down while resources are loading

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#62]
Right now I can't interrupt the resource fetching to switch servers because the server drop down is disabled while the page's resource requests are going out. I have to wait until the page is populated. 

![image](https://user-images.githubusercontent.com/10283712/78289819-bff99780-74f0-11ea-8745-74ceefa78262.png)

It would be nice if I could interrupt the resource fetching to switch servers. Use cases for this are: current server has an issue and is taking too long to respond, made a mistake with the server I want to connect to and want to switch without waiting for page to load.

**Comment by abgeorge7** [comment]
In my redesign, I'm looking at having the server selection page be first so that if an env var isn't set, the user can pick the server first before resources load.
