### ISSUE TITLE
See error with new $snapshot with HAPI

### ISSUE THREAD

**Issue by abgeorge7** [kids-first/kf-ui-fhir-data-dashboard#68]
Error after clicking on a resource to view details (for example, Patient) using HAPI:
```
TypeError: Cannot read property 'count' of undefined
Function.mapStateToProps [as mapToProps]
src/components/ReduxResourceDetails.js:19
  16 |   ? state.resources.allResources[resourceId]
  17 |   : {};
  18 | return {
> 19 |   total: resource.count ? resource.count : 0,
     | ^  20 |   resourceId,
  21 |   resourceFetched: hasResources,
  22 |   baseUrl: state.app.selectedServer.url,
```

**Comment by znatty22** [comment]
@abgeorge7 with which server do you see this error, because I don't think I've deployed the $snapshot fix version yet..(probably time to get a Jenkins pipeline in place for automated deployments 😬)

**Comment by abgeorge7** [comment]
Oh.... does that mean that HAPI hasn't deployed the fix?
Sorry I keep forgetting the architecture haha

**Comment by znatty22** [comment]
@abgeorge7 Interesting 🤔 I completely forgot this was an issue with HAPI too.. Do you want to submit a ticket to Smile CDR to ask about this?

**Comment by abgeorge7** [comment]
@znatty22 this is actually a bug on my side :( working on it.
